### ISSUE TITLE
USER STORY: Create Database Relationships

### ISSUE THREAD

**Issue by FeruzaShokirjonovna** [FeruzaShokirjonovna/Blog#5]
As a **Developer**, I need to define **relationships** between models and import the relationships into working apps models.

_Acceptance Criteria :_

All models are working with the relationships defined, all models that are related to other app models are linked via import statements.

Tasks :

-  Create models for all apps.
-  Set relationships between them via import statements (if applicable).
-  Connect with ElephantSQL server via URL given by ElephantSQL
-  Connect with Cloudinary server via URL given by Cloudinary
-  Run python manage.py makemigrations
-  Run python manage.py migrate

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
